In [1]:
yol = "../../Egzersizler/datasets/titanic/train.csv"
import pandas as pd

In [ ]:
df = pd.read_csv(yol)

In [4]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [15]:
medyanage=df["Age"].median()

TypeError: Cannot convert [22.0 38.0 26.0 35.0 35.0 <bound method Series.median of 0      22.0
                          1      38.0
                          2      26.0
                          3      35.0
                          4      35.0
                                 ...
                          886    27.0
                          887    19.0
                          888     NaN
                          889    26.0
                          890    32.0
                          Name: Age, Length: 891, dtype: float64>    54.0
 2.0 27.0 14.0 4.0 58.0 20.0 39.0 14.0 55.0 2.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    31.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    35.0 34.0 15.0 28.0 8.0 38.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    19.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    40.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    66.0 28.0 42.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    21.0 18.0 14.0 40.0 27.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    3.0 19.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    18.0 7.0 21.0 49.0 29.0 65.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    21.0 28.5 5.0 11.0 22.0 38.0
 45.0 4.0 <bound method Series.median of 0      22.0
          1      38.0
          2      26.0
          3      35.0
          4      35.0
                 ...
          886    27.0
          887    19.0
          888     NaN
          889    26.0
          890    32.0
          Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    29.0 19.0 17.0 26.0 32.0 16.0
 21.0 26.0 32.0 25.0 <bound method Series.median of 0      22.0
                     1      38.0
                     2      26.0
                     3      35.0
                     4      35.0
                            ...
                     886    27.0
                     887    19.0
                     888     NaN
                     889    26.0
                     890    32.0
                     Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    0.83 30.0 22.0 29.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    28.0 17.0 33.0 16.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    23.0 24.0 29.0 20.0 46.0 26.0
 59.0 <bound method Series.median of 0      22.0
      1      38.0
      2      26.0
      3      35.0
      4      35.0
             ...
      886    27.0
      887    19.0
      888     NaN
      889    26.0
      890    32.0
      Name: Age, Length: 891, dtype: float64>    71.0 23.0 34.0 34.0 28.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    21.0 33.0 37.0 28.0 21.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    38.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    47.0 14.5 22.0 20.0 17.0 21.0
 70.5 29.0 24.0 2.0 21.0 <bound method Series.median of 0      22.0
                         1      38.0
                         2      26.0
                         3      35.0
                         4      35.0
                                ...
                         886    27.0
                         887    19.0
                         888     NaN
                         889    26.0
                         890    32.0
                         Name: Age, Length: 891, dtype: float64>    32.5
 32.5 54.0 12.0 <bound method Series.median of 0      22.0
                1      38.0
                2      26.0
                3      35.0
                4      35.0
                       ...
                886    27.0
                887    19.0
                888     NaN
                889    26.0
                890    32.0
                Name: Age, Length: 891, dtype: float64>    24.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    45.0 33.0 20.0 47.0 29.0 25.0
 23.0 19.0 37.0 16.0 24.0 <bound method Series.median of 0      22.0
                          1      38.0
                          2      26.0
                          3      35.0
                          4      35.0
                                 ...
                          886    27.0
                          887    19.0
                          888     NaN
                          889    26.0
                          890    32.0
                          Name: Age, Length: 891, dtype: float64>    22.0
 24.0 19.0 18.0 19.0 27.0 9.0 36.5 42.0 51.0 22.0 55.5 40.5
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    51.0 16.0 30.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    44.0 40.0 26.0 17.0 1.0 9.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    45.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    28.0 61.0 4.0 1.0 21.0 56.0
 18.0 <bound method Series.median of 0      22.0
      1      38.0
      2      26.0
      3      35.0
      4      35.0
             ...
      886    27.0
      887    19.0
      888     NaN
      889    26.0
      890    32.0
      Name: Age, Length: 891, dtype: float64>    50.0 30.0 36.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    9.0 1.0 4.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    45.0 40.0 36.0 32.0 19.0 19.0
 3.0 44.0 58.0 <bound method Series.median of 0      22.0
               1      38.0
               2      26.0
               3      35.0
               4      35.0
                      ...
               886    27.0
               887    19.0
               888     NaN
               889    26.0
               890    32.0
               Name: Age, Length: 891, dtype: float64>    42.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    24.0 28.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    34.0 45.5 18.0 2.0 32.0 26.0
 16.0 40.0 24.0 35.0 22.0 30.0 <bound method Series.median of 0      22.0
                               1      38.0
                               2      26.0
                               3      35.0
                               4      35.0
                                      ...
                               886    27.0
                               887    19.0
                               888     NaN
                               889    26.0
                               890    32.0
                               Name: Age, Length: 891, dtype: float64>
 31.0 27.0 42.0 32.0 30.0 16.0 27.0 51.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    38.0 22.0 19.0 20.5 18.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    35.0 29.0 59.0 5.0 24.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    44.0 8.0 19.0 33.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    29.0 22.0 30.0 44.0 25.0 24.0
 37.0 54.0 <bound method Series.median of 0      22.0
           1      38.0
           2      26.0
           3      35.0
           4      35.0
                  ...
           886    27.0
           887    19.0
           888     NaN
           889    26.0
           890    32.0
           Name: Age, Length: 891, dtype: float64>    29.0 62.0 30.0 41.0
 29.0 <bound method Series.median of 0      22.0
      1      38.0
      2      26.0
      3      35.0
      4      35.0
             ...
      886    27.0
      887    19.0
      888     NaN
      889    26.0
      890    32.0
      Name: Age, Length: 891, dtype: float64>    30.0 35.0 50.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    3.0 52.0 40.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    36.0 16.0 25.0 58.0 35.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    25.0 41.0 37.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    63.0 45.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    7.0 35.0 65.0 28.0 16.0 19.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    33.0 30.0 22.0 42.0 22.0 26.0
 19.0 36.0 24.0 24.0 <bound method Series.median of 0      22.0
                     1      38.0
                     2      26.0
                     3      35.0
                     4      35.0
                            ...
                     886    27.0
                     887    19.0
                     888     NaN
                     889    26.0
                     890    32.0
                     Name: Age, Length: 891, dtype: float64>    23.5 2.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    50.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    19.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    0.92
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    17.0 30.0 30.0 24.0 18.0 26.0
 28.0 43.0 26.0 24.0 54.0 31.0 40.0 22.0 27.0 30.0 22.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    36.0 61.0 36.0 31.0 16.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    45.5 38.0 16.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    29.0 41.0 45.0 45.0 2.0 24.0
 28.0 25.0 36.0 24.0 40.0 <bound method Series.median of 0      22.0
                          1      38.0
                          2      26.0
                          3      35.0
                          4      35.0
                                 ...
                          886    27.0
                          887    19.0
                          888     NaN
                          889    26.0
                          890    32.0
                          Name: Age, Length: 891, dtype: float64>    3.0
 42.0 23.0 <bound method Series.median of 0      22.0
           1      38.0
           2      26.0
           3      35.0
           4      35.0
                  ...
           886    27.0
           887    19.0
           888     NaN
           889    26.0
           890    32.0
           Name: Age, Length: 891, dtype: float64>    15.0 25.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    28.0 22.0 38.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    40.0 29.0 45.0 35.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0
 3      35.0
 4      35.0
        ...
 886    27.0
 887    19.0
 888     NaN
 889    26.0
 890    32.0
 Name: Age, Length: 891, dtype: float64>    30.0 60.0
 <bound method Series.median of 0      22.0
 1      38.0
 2      26.0

In [9]:
df["Age"]=df["Age"].fillna(df["Age"].median)